scitedotai/scite-extension

- src/index.js
fix to #6 
This bugfix dosn't change the behavior in the standard case but improve the behavior in the case describe in #6 
I don't identify why there is different cases in pubmed but I fix this one.
> change innerHTML to textContent for pubmed to prevent unexpected tag

- extension/manifest.json
- index.js
- lib/Tally.js
- package-lock.json
- package.json
- src/background.js
This adds a listener for external messages (from *.scite.ai or localhost).
To test this, one can browse to scite.ai and open chrome devtools with this build of the extension enabled. Replace EXTENSION_ID with the corresponding EXTENSION_ID of the build and loaded extension (`npm run build`).
If all goes well, the output of `chrome.runtime.sendMessage(EXTENSION_ID, 'version', resp => { console.log(resp || 'nope') });` should be an object `{type: "success", version: "1.6.0"}` -- otherwise, it'll print out the string `nope`.
Also, Firefox was complaining about the applications key in the manifest. Thus, I removed it.
> added version listener on external message

- src/background.js
- src/index.js
In order to tell when the user has the extension installed (only on our domains):
+ Inject div with ID `#scite-extension-marker`
+ Emit event on window `scite-extension/loaded`
> [scitedotai/scite#797] Mark pages on our domain w/ div

- src/index.js
some wikipedia pages use this weird styling property and set it to -3.2rem which makes the styling off.
In the future I am considering adding this to the badges themselves add a style reset but for now I will leave it as is.
> [hotfix] reset text indent for wikipedia

- package-lock.json
The node-forge warning I don't think effects us: https://github.com/parcel-bundler/parcel/issues/5145
This addresses the dependabot PRs for ellipsis/ini
> [hotfix] npm audit fix for deps

- src/badges.js
It looks like we are using a pinned version for the badge which maybe a hangover from when we were worried about CSS mismatch, which should no longer be an issue.
> Update badge code to use latest

- README.md
- extension/manifest.json
- package-lock.json
- package.json
- src/badges.js
News articles have different references than Journal articles in Nature. Let's support them
> [hotfix] ensure we support nature news and journal articles

- extension/manifest.json
- package-lock.json
- package.json
- src/badges.js
Unlike other places, google scholar and google URLs present heterogenious URI schemes. I have changed the capture to be DOI only with a bit of scrubbing heursitics based on what I saw ie. ('/full' in frontiers URLs etc.)
I went through a bunch of searches and this really improves badges on google scholar, i couldn't find any other heursitics to strip off but I am sure we will encounter more.
> [hotfix] clean up google doi url captures

- README.md
- extension/manifest.json
- package-lock.json
- package.json
- src/badges.js
- src/index.js
Add to APA results and search
Add a mutation observer for route changes so that if its a dynamically routed SPA we reload the page. 
Fixes a badge issue with APA where the metatag sticks around by introducing a restricted path notion.
- Test on the APA results and search provided in the readme
- Click around to search from a APA page with a badge. It shouldn't have a badge sticking around
- Other things should work as normal.
> [hotfix] add apa results and search and fix badge sticking around on apa / SPAs

- .gitignore
- .postcssrc
- .stylelintrc.json
- .swcrc
- README.md
- build.sh
- config/webpack.common.js
- config/webpack.dev.js
- config/webpack.prod.js
- package-lock.json
- package.json
- src/styles.css
Currently doing further tests on this to see if the build seems more deterministic.
Basically this switches from Parcel to Webpack to be more in line with our other projects. It also uses this as an opportunity to streamline the build a bit (dev mode is now much quicker as it does not build a production bundle each time + only needs one npm command).
This also adds stylelint which was mentioned in the package.json but not installed.
> [scitedotai/scite#3785] Move to webpack for hopefully better builds

- src/index.js
Fixes: https://github.com/scitedotai/scite/issues/2657
The DOI is provided at `dc.identifier` but it is the meta tag `property` attribute rather than `name` here: https://www.researchgate.net/publication/336759980_Identification_of_a_Synergistic_Multi-Drug_Combination_Active_in_Cancer_Cells_via_the_Prevention_of_Spindle_Pole_Clustering
> [fix scitedotai/scite#2657] Fix researchgate popup

- .circleci/config.yml
- config/webpack.common.js
- extension/manifest.json
- jest.config.js
- package-lock.json
- package.json
- setupTests.js
- src/__tests__/pdf.test.js
- src/badges.js
- src/index.js
- src/pdf.js
- src/reference-matching.js
We want to support badges on PDFs universally without sending to ref check. We can do so by parsing the DOI from the PDF or the title and first author surname for glutton.
This adds PDF.js to the extension to parse PDF objects to find those items.
The heuristics for finding those are as follows:
This currently only works on chrome (maybe safari and edge have to test). Since Firefox has a different PDF flow we'd have to address differently.
This does not yet work for local PDFs.
We also add testing and CI to be a bit more rigerious.
Using Chrome open scholarly PDFs online! Open ones that have a scite report attached.
Is the badge showing up? is it the right report?
I just opened arxiv and acl and searched things like "transliteration" and "zero-shot" and opened the oldest PDFs (since new …
> GH 3881/add pdf parser

- extension/manifest.json
- package-lock.json
- package.json
- src/badges.js
- src/index.js
- [GH-3879] ensure that gmail does not have badges injected (it doesn't look good)
- [GH-3921] add ads work around and fix poppedup state for SPAs 
ADS actually has a broken metadata section so metadata for citation_doi were just not working. I added a work around using the page DOI for now.
Also I noticed that SPAs were a bit broken because the popped up state was not getting reset! So when you reroute a new popup was not getting created! I fixed that as well.
Testing:
For ADS go here:
-https://ui.adsabs.harvard.edu/abs/2022FrPhy..1734501X/abstract
- search somethign new
- click a few links and ensure the badge changes!
- sometimes the badge stays due to their SPA bug.
For JSTOR go here: 
- https://github.com/scitedotai/scite/issues/3921
- Other JSTOR articles work anyway
> GH 3921/add support for ads

- extension/manifest.json
- package-lock.json
- src/badges.js
- src/index.js
Based on https://github.com/scitedotai/scite-extension/issues/64 
Part of this is inadvertanly removing badge removal during the last PR.
We need to remove semantic scholar badges for now because they are being problematic:
1. They stick around on layout changes in semantic scholar (I haven't though of a way to solve this)
2. Asyncly injected badges after changing the page get inserted in wrong places (I have solved this by changing when we insert badges to be more robust)
We can consider adding badges for semantic scholar and solving 1 later.
> [GH-4216] remove semantic scholar badges and improve badge clearing

- src/badge/main.js
Trying this locally in incognito it seems to work... I think in the transition to the mega repo this file must have accidentally gotten unincluded.
Pushing to stage to test there. Locally I see that now the icon font is downloaded in private mode.
/Cc @u-ashish
> [hotfix] Include font files for badge

- src/background.js
We may also consider changing the utm_campaign:
```
&utm_source=generic&utm_medium=plugin&utm_campaign=plugin-citation-search
```
Not sure what would be most helpful there but this leaves it the same rn
/Cc @jmnicholson @u-ashish
> [scitedotai/scite#5699] Change search link to assistant one

- README.md
- package-lock.json
- package.json
- src/badge/main.js
- src/components/SectionTally.js
- src/components/Tally.js
- src/components/Tooltip.js
As part of we want the AG team to be able to point to scite staging in their test environment.
- Add `use-test-env` as an optional flag we pick up from the `el.dataset`
- When it is set to `'true'`, we point to `staging.scite.ai` as the baseUrl
- By default, this flag is set to `false` so it always points to production.
- Update README
- Bump package version
I think after merging I just have to deploy it to staging and prod by tagging and that's it right?
> SCITE-1045 | Add optional use-test-env flag to point to scite staging

- package-lock.json
- package.json
- src/components/Tooltip.js
With the Smart Citations badge, when users disable `showZero`, the tooltip will be missing when `citingPublications > 0` but `tally = 0` (note that `tally` represents the sum of smart cites, not dumb cites).
To see it happen on prod:
- go to https://scite.ai/badge
- for the smart cite badge, use the DOI=10.1016/j.biopsych.2005.08.012
- the tallies are there, tooltip will work
now, try again:
- use DOI=10.1097/MOU.0000000000000026
- note that there are 2 dumb cites but 0 smart cites
- badge will show but tooltip will not
this is because the check to showTooltip uses just `tally.total` when it should also factor in `tally.citingPublications`. Unfortunately the section tally doesn't return that right now, so add a conditional to check accordingly based on the tally type to avoid any …
> [noref] For smart_citations, include citingPublications count when deciding whether there are tallies

- extension/manifest.json
Works in Chrome
Something weird with web-ext and other browsers to working that out ATM.
> [hotfix] update to manifest v3

- src/components/Count.js
- src/util/getCountNumber.js
<hr>
Adding functionality to check `count` value and return it as Number. It helps to prevent errors when count is not a String and tries to use the `replaceAll()` string method.
> Fix s.replaceAll error
