- src/index.js
I add the management of Sci-hub with your amazing extension.
I hope this will be helpful
> add sci-hub DOI search function

- package-lock.json
- package.json
- src/index.js
- src/test.js
Don't load the extension on our domain... If this is approved I will merge + handle both releases.
> [1510] No extension on (staging.)scite.ai

- package-lock.json
- package.json
For https://github.com/scitedotai/scite/issues/1214
> [1214] Use new scite-widget version

- README.md
> [hotfix] Add release instructions for scite employees

- .gitignore
- README.md
- package-lock.json
- package.json
- src/index.js
- Add web-ext to dev workflow
- Add badges on wikipedia
ToDo:
> [GH-1897] add badges to wikipedia pages

- README.md
- extension/manifest.json
- package-lock.json
- package.json
- src/badges.js
- src/index.js
refactor into its own module with a rule table
Add support for pubmed and pmc
Also adding the DONT_POPUP_HOST restriction for pop up to fix the bug mason noticed with wikipedia
I added nature, elife and google scholar as well
Test wikipedia extension locally try to find a page with one reference the pop up shouldn't work but bdages should insert. Pop up should work on other pages.
Test Pubmed and Pubmed Central search results, citations, similar aticles and references
Test on firefox and chrome
> [GH-1867] Add Pubmed and Pubmed Central

- README.md
- extension/manifest.json
- package.json
- src/badges.js
- src/index.js
> [GH-1867] add PNAS and ePMC

- package-lock.json
- package.json
- src/badges.js
sometimes PubMed Central was failing. Why? because i forgot to spread out one of the query selectors 😬 I will consider using just a multitple selector instead when i refector this to avoid the error.
Also added optional chaining all over for robuseness.
> [hotfix] add missing spread operator and add optional chaining for robuseness

- package-lock.json
- package.json
Rebuild `pacakge-json.lock` to get latest `scite-widget` code
> [scitedotai/scite#2537] Bump widget commit

- README.md
- extension/manifest.json
- package-lock.json
- package.json
- src/badges.js
- src/index.js
fix [GH-2596] add ORCID to list of long delay hosts
fix [GH-2294] add generic find doi from link for popup
[GH-1897] support connected papers, peerj, clinical trials
Do badges load on long ORCID records,  does the paper linked in gh-2294 have the correct DOI? does connected papers have badges in the node panel on the right?
> Gh 1897/add more extension links

- README.md
- extension/manifest.json
- package-lock.json
- package.json
- src/badges.js
- src/index.js
Adds:
- lens
- biomedcentral
- research gate 
Changes:
- connected papers uses a periodic waiter since its a SPA and we need to reload sometimes when a graph is being created or routing is changed
Refactors:
- factor out common styles and regexes
- clarify some names
> [Gh 1897] support more sites

- src/badges.js
Toward: https://github.com/scitedotai/scite/issues/2650
Tested locally in FF.... Seems to work and seems like a low risk change.
> [scitedotai/scite#2650] Disable the ol tooltip

- README.md
- extension/manifest.json
- package-lock.json
- package.json
- src/badges.js
- src/styles.css
- [GH-2819] hide scite popup on print
- [GH-2801] add break statement to not add duplicate springer badges
- [GH-2733] add badges to scielo
- [GH-2837] add publications count to badge and popup
**HOLD**: Merge widget then badge then this (and swap to prod cdn and widget#master)
> Add publication count to extension and other goodies (scielo, springer badge dupes, hide popup on print css)

- extension/manifest.json
- package-lock.json
- package.json
- src/badges.js
ORCID released a fancy new website.
This will fix it.
TODO:
- release all this
> [hotfix] fix orcid display not working

- package-lock.json
- package.json
- src/badges.js
- src/index.js
- src/reference-matching.js
Fixes: https://github.com/scitedotai/scite/issues/3494
Been testing this bad boy locally seems to work pretty well.
Depends on: https://github.com/scitedotai/scite-api-fastapi/pull/403/files
> [scitedotai/scite#3494] Reference matching for scholar

- extension/manifest.json
- package-lock.json
- src/index.js
Depends on: https://github.com/scitedotai/scite-widget/pull/29 ( you will need to change the #master on the widget to that commit and reinstall the extension to get the code (i recommend deleteing node modules since its being a dingus)
> [GH-2630] use hideable tally

- package-lock.json
- package.json
- src/badges.js
Fixes: https://github.com/scitedotai/scite/issues/4270
Depends on: https://github.com/scitedotai/scite-badge/pull/38
Import badge as library instead of injecting script onto page.
> [fix scitedotai/scite#4270] Import badge as library

- src/badge/main.js
- src/components/Tooltip.js
Realized we also need to hide in the tooltip for this
> [scitedotai/scite#5562] Also hide in tooltip

- src/index.js
Fixes: https://github.com/scitedotai/scite/issues/5727
No idea how this worked before lol, afaik I didn't touch this
/Cc @u-ashish
> [scitedotai/scite#5727] Fix browser = chrome assignment

- extension/manifest.json
- package.json
- src/index.js
- [GH-6033] add wos support
- [GH-6033] bump to version 1.36.0
> GH 6033/add wos support

- extension/manifest.json
- package-lock.json
- package.json
- [hotfix] add popper core depedency
- [hotfix] bump to 1.36.2
> [hotfix] add popper core depedency

- README.md
- src/badge/main.js
- src/badge/test-page.js
- src/components/Tooltip.js
- src/styles/Tooltip.css
Karger requested:
- Fix the active link state color and add an ID
- Make it so the badge can be opened using by a keyboard for people implementing accessability issues
> [hotfix] add accessability fixes that are requested

- README.md
- src/badge/main.js
- src/badge/test-page.js
- src/components/Count.js
- src/components/Icon.js
- src/components/Tally.js
- src/styles/Count.css
- src/styles/Icon.css
- src/styles/Tally.css
> Add badge vertical compact mode

- src/components/Count.js
- src/styles/Count.css
*Applies only for `vertical-compact` mode
> add conditional font size for counters
